spring:
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
          - Path=/account/**
        - id: address-service
          uri: lb://address-service
          predicates:
          - Path=/address/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8585

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info
  tracing:
    sampling:
      probability: 1.0
springdoc:
  swagger-ui:
    urls:
      - name: address
        url: /v3/api-docs/address
      - name: account
        url: /v3/api-docs/account

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"




