spring:
  application:
    name: gateway-service
  main:
    web-application-type: none
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
          - Path=/api/v1/account/**
        - id: address-service
          uri: lb://address-service
          predicates:
          - Path=/api/v1/address/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        discovery:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8585

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: address
        url: /v3/api-docs/address
      - name: account
        url: /v3/api-docs/account


